// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Sharp.Models;
using System;

namespace Sharp.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Sharp.Models.Store", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address")
                        .HasMaxLength(100);

                    b.Property<string>("City")
                        .HasMaxLength(50);

                    b.Property<string>("DataBase")
                        .HasMaxLength(50);

                    b.Property<int>("Port");

                    b.Property<string>("PostCode")
                        .HasMaxLength(10);

                    b.Property<string>("PublicIp")
                        .HasMaxLength(50);

                    b.Property<string>("StoreId")
                        .HasMaxLength(50);

                    b.Property<string>("StoreName")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Stores");
                });

            modelBuilder.Entity("Sharp.Models.UserStore", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("StoreId")
                        .HasMaxLength(50);

                    b.Property<string>("UserId")
                        .HasMaxLength(50);

                    b.Property<string>("UserRole")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("UserStores");
                });
#pragma warning restore 612, 618
        }
    }
}
